const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("api", {
  getTableConfig: () => ipcRenderer.invoke("get-table-config"),
  getOwners: (tableName) => ipcRenderer.invoke("get-owners", tableName),
  getVehicles: (tableName, owner) => ipcRenderer.invoke("get-vehicles", tableName, owner),
  searchVehicles: (tableName, searchQuery) => ipcRenderer.invoke("search-vehicles", tableName, searchQuery),
  updateExpiry: (tableName, ids, newValue) => ipcRenderer.invoke("update-expiry", tableName, ids, newValue),
  updateStatus: (tableName, ids, newStatus) => ipcRenderer.invoke("update-status", tableName, ids, newStatus),
  getNextCustomerId: () => ipcRenderer.invoke("get-next-customer-id"),
  searchCustomers: (q) => ipcRenderer.invoke("search-customers", q),
  listCustomers: (q) => ipcRenderer.invoke("list-customers", q),
  insertCustomer: (data) => ipcRenderer.invoke("insert-customer", data),
  updateCustomer: (data) => ipcRenderer.invoke("update-customer", data),
  deleteCustomer: (maKhachHang) => ipcRenderer.invoke("delete-customer", maKhachHang),
  insertVehicle: (data) => ipcRenderer.invoke("insert-vehicle", data),
  updateVehicle: (data) => ipcRenderer.invoke("update-vehicle", data),
  deleteVehicle: (tableName, bienSo) => ipcRenderer.invoke("delete-vehicle", tableName, bienSo),
  confirmDialog: (opts) => ipcRenderer.invoke("confirm-dialog", opts),
  testConnection: () => ipcRenderer.invoke("test-connection"),
  getAppVersion: () => ipcRenderer.invoke("get-app-version"),

  onUpdateAvailable: (cb) => ipcRenderer.on("update-available", (_e, version) => cb(version)),
  onUpdateNotAvailable: (cb) => ipcRenderer.on("update-not-available", () => cb()),
  onUpdateDownloadProgress: (cb) => ipcRenderer.on("update-download-progress", (_e, percent) => cb(percent)),
  onUpdateDownloaded: (cb) => ipcRenderer.on("update-downloaded", () => cb()),
  onUpdateError: (cb) => ipcRenderer.on("update-error", (_e, msg) => cb(msg)),
  downloadUpdate: () => ipcRenderer.invoke("update-download"),
  installUpdate: () => ipcRenderer.invoke("update-install"),
  checkForUpdate: () => ipcRenderer.invoke("update-check"),
});
